[package]
name = "sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delta-pico-rust = { path = "../rust", default-features = false }
minifb = "0.22.0"
