[package]
name = "delta-pico-rust"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[build-dependencies]
cbindgen = "0.7.1"

[lib]
crate-type = ["staticlib"]

[dependencies]
rbop = { path = "../../rbop" }
rust_decimal = { version = "1.9.0", default-features = false }
