name: Test in simulator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DELTA_PICO_FFPYTHON: /usr/bin/python3

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - name: Install nightly Rust toolchain
      uses: dtolnay/rust-toolchain@nightly
    - name: Install libxkbcommon-dev
      run: sudo apt-get install libxkbcommon-dev
    - name: Install FontForge
      run: |
        sudo apt update -y
        sudo apt install fontforge -y
        sudo apt install python3-fontforge -y
    - name: Install Pillow
      run: |
        sudo apt build-dep python-imaging
        sudo pip3 install pillow
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        repository: AaronC81/delta-pico
        path: ./delta-pico
    - name: Checkout simulator
      uses: actions/checkout@v3
      with:
        repository: AaronC81/delta-pico-sim
        path: ./delta-pico-sim
    - name: Checkout rbop
      uses: actions/checkout@v3
      with:
        repository: AaronC81/rbop
        path: ./rbop
    - name: Run tests in simulator
      run: cargo run --verbose -- --test
      working-directory: ./delta-pico-sim
